//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VT_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tree()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int TreeId { get; set; }
        public int LoaiId { get; set; }
        public string TenTree { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public string TinhTrang { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual Loai Loai { get; set; }
    }
}
