//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<< HEAD:G_Shop/G_Shop/Models/GShop.Context.cs
    public partial class GShopEntities2 : DbContext
    {
        public GShopEntities2()
            : base("name=GShopEntities2")
=======
    public partial class GShopEntities1 : DbContext
    {
        public GShopEntities1()
            : base("name=GShopEntities3")
>>>>>>> parent of f6eb24b... Revert "change name of "context" to "GShopEntities1"":G_Shop/G_Shop/Models/Model.Context.cs
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaThe> CaThes { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
    }
}
