//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G_Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GShopEntities1 : DbContext
    {
<<<<<<< Updated upstream:G_Shop/G_Shop/Models/Model2.Context.cs
        public GShopEntities2()
            : base("name=GShopEntities2")
=======
        public GShopEntities1()
            : base("name=GShopEntities1")
>>>>>>> Stashed changes:G_Shop/G_Shop/Models/Model1.Context.cs
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaThe> CaThes { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<Giong> Giongs { get; set; }
        public virtual DbSet<GoiY> GoiYs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
    }
}
